# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6cbf9aed45d3a873eea5358b7872dd44e56a406d1f66d89a6c7137aa01cb4dd64503f0c57bfec37e533282f9f24f4c158ff176340e32fa17520e6ee2f547e5c

test:
  secret_key_base: 93ba02d8c526e8d597ee24e8d39ae4a07d67df4ed69d52ba27df67dab3c517b88445a79015dbc5e3a820fcc2f0746b39e3f317e6080e797a586ea2386fecb435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
